server:
  port: 8003
spring:
  profiles:
    active: dev
  application:
    name: service-vod
  redis:
    host: 192.168.94.128
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-idle: 5
        max-active: 20
        max-wait: -1
        min-idle: 0
# 最大上传单个文件大小：默认1M
  servlet:
    multipart:
      max-file-size: 1024MB
# 最大置总上传的数据大小 ：默认10M
      max-request-size: 1024MB
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848


aliyun:
  oss:
    access-key-id: *****************
    access-key-secret: *****************
