server:
  port: 8008
spring:
  application:
    name: service-statistics
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: kly
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 192.168.94.128
    port: 6379
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-idle: 5
        min-idle: 0
        max-wait: -1
        max-active: 20
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
mybatis-plus:
  mapper-locations: classpath:/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
