server:
  port: 8006
spring:
  application:
    name: service-msm
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: kly
  profiles:
    active: dev
  redis:
    host: 192.168.94.128
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-idle: 5
        max-active: 20
        max-wait: -1
        min-idle: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
